package schemaguard

import (
	"encoding/json"
	"time"

	"github.com/tonitienda/agent-smith/schema"
)

// Directory layout (paths relative to the repo root) for the committed guard
// artifacts. The cmd/schema-guard tool writes here with -update; the package
// tests read the same files via package-relative paths.
const (
	// TestdataDir holds the guard's committed artifacts.
	TestdataDir = "internal/schemaguard/testdata"
	// BaselineFile is the frozen schema descriptor the diff compares against.
	BaselineFile = TestdataDir + "/schema_baseline.json"
	// GoldenDir holds serialized v1 sessions kept permanently for the
	// forward-compatibility (parse) guarantee.
	GoldenDir = TestdataDir + "/golden"
)

// goldenTS is a fixed timestamp so regenerated golden files are byte-stable
// across runs (no spurious diffs from wall-clock time).
var goldenTS = time.Date(2026, 6, 13, 12, 0, 0, 0, time.UTC)

func intPtr(i int) *int           { return &i }
func floatPtr(f float64) *float64 { return &f }

// GeneratedGoldens returns the golden session documents that are derived from
// the schema types, keyed by file name. They are built with fixed IDs and
// timestamps so `-update` is deterministic. These are regenerated by the tool;
// hand-written goldens (e.g. forward-compat fixtures with unknown fields) live
// alongside them in GoldenDir and are not overwritten.
func GeneratedGoldens() map[string]schema.Document {
	return map[string]schema.Document{
		"session-basic.json": basicSession(),
		"session-full.json":  fullSession(),
	}
}

// basicSession is a small, realistic v1 session: a typical turn with only the
// fields a minimal harness would populate.
func basicSession() schema.Document {
	system := block("blk_sys", schema.KindText, schema.RoleSystem)
	system.Text = &schema.TextBody{Text: "You are a helpful coding agent."}

	user := block("blk_user", schema.KindText, schema.RoleUser)
	user.Text = &schema.TextBody{Text: "List the files in the repo root."}

	reasoning := block("blk_think", schema.KindReasoning, schema.RoleAssistant)
	reasoning.Reasoning = &schema.ReasoningBody{Text: "I should run ls.", ReplayScope: schema.ReplayPortable}

	call := block("blk_call", schema.KindToolCall, schema.RoleAssistant)
	call.StopReason = "tool_use"
	call.ToolCall = &schema.ToolCallBody{
		ToolUseID: "toolu_basic_1",
		Name:      "shell",
		Arguments: json.RawMessage(`{"cmd":"ls"}`),
		ToolKind:  schema.ToolKindClient,
	}

	result := block("blk_result", schema.KindToolResult, schema.RoleTool)
	result.ToolResult = &schema.ToolResultBody{
		ToolUseID: "toolu_basic_1",
		Content:   []schema.Part{{Type: "text", Text: "README.md\ngo.mod"}},
		ExitCode:  intPtr(0),
		Stdout:    "README.md\ngo.mod\n",
	}

	answer := block("blk_answer", schema.KindText, schema.RoleAssistant)
	answer.StopReason = "end_turn"
	answer.Tokens = &schema.Tokens{Input: intPtr(412), Output: intPtr(37)}
	answer.Text = &schema.TextBody{Text: "The repo root contains README.md and go.mod."}

	return schema.NewDocument(system, user, reasoning, call, result, answer)
}

// fullSession is a maximal-coverage v1 session: one block per content kind with
// every envelope and body field populated, so the corpus exercises the entire
// shape. It mirrors the maximal fixture the schema package round-trips, kept
// here independently as a frozen on-disk v1 artifact.
func fullSession() schema.Document {
	text := full("blk_full_text", schema.KindText, schema.RoleAssistant)
	text.Text = &schema.TextBody{
		Text:        "hello",
		Subtype:     schema.TextSubtypeNormal,
		Parts:       []schema.Part{{Type: "image", MediaType: "image/png", URL: "https://x/y.png"}},
		Citations:   []schema.Citation{{Type: "web", URL: "https://src", Title: "Src", CitedText: "quote", Source: "live_search"}},
		Annotations: []json.RawMessage{json.RawMessage(`{"type":"url_citation"}`)},
		Ext:         map[string]json.RawMessage{"tb": json.RawMessage(`"z"`)},
	}

	call := full("blk_full_call", schema.KindToolCall, schema.RoleAssistant)
	call.ToolCall = &schema.ToolCallBody{
		ToolUseID:     "toolu_full_1",
		Name:          "shell",
		Arguments:     json.RawMessage(`{"cmd":"ls"}`),
		ArgumentsRaw:  `{"cmd":"ls"}`,
		ToolKind:      schema.ToolKindClient,
		ToolSubtype:   "web_search",
		ParallelGroup: "grp_1",
		MCPServer:     "github",
		Ext:           map[string]json.RawMessage{"cb": json.RawMessage(`1`)},
	}

	result := full("blk_full_result", schema.KindToolResult, schema.RoleTool)
	result.ToolResult = &schema.ToolResultBody{
		ToolUseID:         "toolu_full_1",
		Content:           []schema.Part{{Type: "text", Text: "file listing"}},
		IsError:           true,
		Citations:         []schema.Citation{{URL: "https://c"}},
		ExitCode:          intPtr(0),
		Stdout:            "out",
		Stderr:            "err",
		StructuredContent: json.RawMessage(`{"files":["a","b"]}`),
		Truncated:         true,
		OffloadRef:        "blob://123",
		Ext:               map[string]json.RawMessage{"rb": json.RawMessage(`"r"`)},
	}

	fileRead := full("blk_full_fileread", schema.KindFileRead, schema.RoleHarness)
	fileRead.FileRead = &schema.FileReadBody{
		Path:        "/repo/go.mod",
		Range:       &schema.LineRange{StartLine: intPtr(1), EndLine: intPtr(3), StartByte: intPtr(0), EndByte: intPtr(64)},
		Content:     "module ...",
		ContentHash: "sha256:abc",
		OffloadRef:  "blob://456",
		Error:       "",
		ProducedBy:  "toolu_read",
		MediaType:   "text/plain",
		Source:      schema.FileSourceTool,
		Ext:         map[string]json.RawMessage{"fb": json.RawMessage(`"f"`)},
	}

	reasoning := full("blk_full_reasoning", schema.KindReasoning, schema.RoleAssistant)
	reasoning.Reasoning = &schema.ReasoningBody{
		Text:        "thinking...",
		Summary:     []string{"step 1", "step 2"},
		Encrypted:   "OPAQUE==",
		Signature:   "sig_abc",
		Redacted:    true,
		ReplayScope: schema.ReplaySameModelOnly,
		Ext:         map[string]json.RawMessage{"rsb": json.RawMessage(`"q"`)},
	}

	doc := schema.NewDocument(text, call, result, fileRead, reasoning)
	doc.Ext = map[string]json.RawMessage{"doc_x": json.RawMessage(`1`)}
	return doc
}

// block returns a minimally-populated envelope (only the five required fields).
func block(id string, kind schema.Kind, role schema.Role) schema.Block {
	return schema.Block{ID: id, Kind: kind, Seq: 0, TS: goldenTS, Role: role}
}

// full returns a maximally-populated envelope (every optional set) for the
// given kind, so the full-session golden exercises the entire shared shape.
func full(id string, kind schema.Kind, role schema.Role) schema.Block {
	return schema.Block{
		ID:         id,
		Kind:       kind,
		Seq:        7,
		TS:         goldenTS,
		Role:       role,
		StopReason: "end_turn",
		Provenance: &schema.Provenance{
			Producer:    "anthropic-adapter",
			RequestID:   "req_1",
			ResponseID:  "resp_1",
			TurnID:      "turn_1",
			DerivedFrom: []string{"blk_a", "blk_b"},
			Ext:         map[string]json.RawMessage{"prov_x": json.RawMessage(`"y"`)},
		},
		Provider: &schema.Provider{
			Vendor:     "anthropic",
			Surface:    "messages",
			Model:      "claude-opus-4-8",
			NativeType: "text",
			NativeID:   "msg_123",
			Ext:        map[string]json.RawMessage{"raw": json.RawMessage(`{"k":1}`)},
		},
		Thread: &schema.Thread{
			ThreadID:       "t_1",
			ParentBlockID:  "blk_parent",
			ParentThreadID: "t_root",
			AgentID:        "agent_7",
			IsSidechain:    true,
			Ext:            map[string]json.RawMessage{"th": json.RawMessage(`true`)},
		},
		Attribution: &schema.Attribution{
			Skill:     "deep-research",
			MCPServer: "github",
			MCPTool:   "list_issues",
			Tool:      "Grep",
			Hook:      "PostToolUse",
			Ext:       map[string]json.RawMessage{"a": json.RawMessage(`1`)},
		},
		Tokens: &schema.Tokens{
			Input:        intPtr(100),
			Output:       intPtr(0),
			CacheRead:    intPtr(20),
			CacheWrite:   intPtr(30),
			Reasoning:    intPtr(5),
			CacheWrite5m: intPtr(11),
			CacheWrite1h: intPtr(22),
			Iterations:   []schema.Tokens{{Input: intPtr(50), Output: intPtr(60)}},
			Ext:          map[string]json.RawMessage{"tk": json.RawMessage(`"v"`)},
		},
		CostUSD:   floatPtr(0.0123),
		UsageMeta: &schema.UsageMeta{ServiceTier: "standard", Speed: "fast", ServerToolUse: json.RawMessage(`{"web_search_requests":2}`)},
		Cache: &schema.Cache{
			Mode:        schema.CacheModeExplicit,
			Breakpoints: []schema.CacheBreakpoint{{BlockID: "blk_bp", TTL: "5m"}},
			TTL:         "5m",
		},
		ExcludedBy: []string{"evt_1"},
		Ext:        map[string]json.RawMessage{"env_x": json.RawMessage(`{"nested":[1,2,3]}`)},
	}
}
